
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
